spring:
  application:
    name: applyflow

  datasource:
    url: jdbc:postgresql://localhost:5432/applyflow
    username: applyuser
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---

jwt:
  secret: a5YsbT1bLBJvv3Qtc2VjdXJpdHktand0LXR1dG9yaYAsLSppd11vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK
  expiration: 3600000